 Network rinha-nginx-2024q1  Creating
 Network rinha-nginx-2024q1  Created
 Container gldmelo-py-fastapi-db-1  Creating
 Container gldmelo-py-fastapi-db-1  Created
 Container gldmelo-py-fastapi-api02-1  Creating
 Container gldmelo-py-fastapi-api01-1  Creating
 Container gldmelo-py-fastapi-api02-1  Created
 Container gldmelo-py-fastapi-api01-1  Created
 Container gldmelo-py-fastapi-nginx-1  Creating
 Container gldmelo-py-fastapi-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
db-1     | performing post-bootstrap initialization ... ok
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | waiting for server to start....2024-02-20 23:29:18.194 GMT [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-20 23:29:18.194 GMT [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-20 23:29:18.196 GMT [51] LOG:  database system was shut down at 2024-02-20 23:29:16 GMT
db-1     | 2024-02-20 23:29:18.198 GMT [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | DO
db-1     | CREATE FUNCTION
db-1     | CREATE FUNCTION
db-1     | CREATE INDEX
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-20 23:29:18.477 GMT [48] LOG:  received fast shutdown request
db-1     | .2024-02-20 23:29:18.477 GMT [48] LOG:  aborting any active transactions
db-1     | 2024-02-20 23:29:18.479 GMT [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-20 23:29:18.479 GMT [49] LOG:  shutting down
db-1     | 2024-02-20 23:29:18.479 GMT [49] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-20 23:29:18.874 GMT [49] LOG:  checkpoint complete: wrote 937 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.208 s, sync=0.001 s, total=0.396 s; sync files=0, longest=0.000 s, average=0.000 s; distance=4297 kB, estimate=4297 kB; lsn=0/191CDF0, redo lsn=0/191CDF0
db-1     | 2024-02-20 23:29:18.880 GMT [48] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-20 23:29:18.993 GMT [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-20 23:29:18.993 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-20 23:29:18.993 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-20 23:29:18.993 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-20 23:29:18.995 GMT [66] LOG:  database system was shut down at 2024-02-20 23:29:18 GMT
db-1     | 2024-02-20 23:29:18.998 GMT [1] LOG:  database system is ready to accept connections
api01-1 exited with code 3
api02-1 exited with code 3
nginx-1  | 2024/02/20 23:29:22 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:25 [error] 29#29: *1 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:27 [error] 29#29: *4 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:29 [error] 29#29: *5 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:31 [error] 29#29: *6 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:36 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:39 [error] 29#29: *7 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:41 [error] 29#29: *10 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:43 [error] 29#29: *11 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:45 [error] 29#29: *12 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:50 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:53 [error] 29#29: *13 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:55 [error] 29#29: *16 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:57 [error] 29#29: *17 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:29:59 [error] 29#29: *18 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:05 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:08 [error] 29#29: *19 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:10 [error] 29#29: *22 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:12 [error] 29#29: *23 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:14 [error] 29#29: *24 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:19 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.3:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:22 [error] 29#29: *25 connect() failed (113: No route to host) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.21.0.4:8000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:24 [error] 29#29: *28 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:26 [error] 29#29: *29 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/20 23:30:28 [error] 29#29: *30 no live upstreams while connecting to upstream, client: 172.21.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-20 23:30:31.164 GMT [1] LOG:  received fast shutdown request
db-1     | 2024-02-20 23:30:31.164 GMT [1] LOG:  aborting any active transactions
db-1     | 2024-02-20 23:30:31.166 GMT [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
db-1     | 2024-02-20 23:30:31.166 GMT [64] LOG:  shutting down
db-1     | 2024-02-20 23:30:31.166 GMT [64] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-20 23:30:31.167 GMT [64] LOG:  checkpoint complete: wrote 46 buffers (0.3%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.001 s, sync=0.001 s, total=0.002 s; sync files=0, longest=0.000 s, average=0.000 s; distance=94 kB, estimate=94 kB; lsn=0/1934608, redo lsn=0/1934608
db-1     | 2024-02-20 23:30:31.170 GMT [1] LOG:  database system is shut down
db-1 exited with code 0
