 Network rinha-gateway-2024q1  Creating
 Network rinha-gateway-2024q1  Created
 Container marcusdacoregio-db-1  Creating
 Container marcusdacoregio-db-1  Created
 Container marcusdacoregio-api01-1  Creating
 Container marcusdacoregio-api02-1  Creating
 Container marcusdacoregio-api01-1  Created
 Container marcusdacoregio-api02-1  Created
 Container marcusdacoregio-nginx-1  Creating
 Container marcusdacoregio-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... Etc/UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
api02-1  | 
api02-1  |   .   ____          _            __ _ _
api02-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api02-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api02-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api02-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api02-1  |  =========|_|==============|___/=/_/_/_/
api02-1  |  :: Spring Boot ::                (v3.2.2)
api02-1  | 
api02-1  | 2024-02-19T11:34:49.136Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Starting AOT-processed RinhaApiApplication using Java 21.0.2 with PID 1 (/workspace/com.marcusdacoregio.rinhaapi.RinhaApiApplication started by cnb in /workspace)
api02-1  | 2024-02-19T11:34:49.136Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : No active profile set, falling back to 1 default profile: "default"
api02-1  | 2024-02-19T11:34:49.215Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8081 (http)
api02-1  | 2024-02-19T11:34:49.216Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api02-1  | 2024-02-19T11:34:49.216Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
api02-1  | 2024-02-19T11:34:49.227Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api02-1  | 2024-02-19T11:34:49.227Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 91 ms
api02-1  | 2024-02-19T11:34:49.247Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
api01-1  | 
api01-1  |   .   ____          _            __ _ _
api01-1  |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
api01-1  | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
api01-1  |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
api01-1  |   '  |____| .__|_| |_|_| |_\__, | / / / /
api01-1  |  =========|_|==============|___/=/_/_/_/
api01-1  |  :: Spring Boot ::                (v3.2.2)
api01-1  | 
api01-1  | 2024-02-19T11:34:49.264Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Starting AOT-processed RinhaApiApplication using Java 21.0.2 with PID 1 (/workspace/com.marcusdacoregio.rinhaapi.RinhaApiApplication started by cnb in /workspace)
api01-1  | 2024-02-19T11:34:49.264Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : No active profile set, falling back to 1 default profile: "default"
api01-1  | 2024-02-19T11:34:49.282Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
api01-1  | 2024-02-19T11:34:49.315Z  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
api01-1  | 2024-02-19T11:34:49.315Z  INFO 1 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
api01-1  | 2024-02-19T11:34:49.323Z  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
api01-1  | 2024-02-19T11:34:49.323Z  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 59 ms
api01-1  | 2024-02-19T11:34:49.334Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-19 11:34:50.262 UTC [48] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-19 11:34:50.265 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-19 11:34:50.275 UTC [51] LOG:  database system was shut down at 2024-02-19 11:34:49 UTC
db-1     | 2024-02-19 11:34:50.281 UTC [48] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db-1     | 
db-1     | waiting for server to shut down....2024-02-19 11:34:50.467 UTC [48] LOG:  received fast shutdown request
db-1     | 2024-02-19 11:34:50.473 UTC [48] LOG:  aborting any active transactions
db-1     | 2024-02-19 11:34:50.480 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
db-1     | 2024-02-19 11:34:50.480 UTC [49] LOG:  shutting down
db-1     | 2024-02-19 11:34:50.484 UTC [49] LOG:  checkpoint starting: shutdown immediate
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
db-1     | 2024-02-19 11:34:50.970 UTC [49] LOG:  checkpoint complete: wrote 923 buffers (5.6%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.259 s, sync=0.215 s, total=0.490 s; sync files=301, longest=0.196 s, average=0.001 s; distance=4257 kB, estimate=4257 kB; lsn=0/1913068, redo lsn=0/1913068
db-1     | 2024-02-19 11:34:50.975 UTC [48] LOG:  database system is shut down
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-19 11:34:51.092 UTC [1] LOG:  starting PostgreSQL 16.1 (Debian 16.1-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1     | 2024-02-19 11:34:51.092 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-19 11:34:51.092 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-19 11:34:51.098 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-19 11:34:51.105 UTC [64] LOG:  database system was shut down at 2024-02-19 11:34:50 UTC
db-1     | 2024-02-19 11:34:51.111 UTC [1] LOG:  database system is ready to accept connections
api02-1  | 2024-02-19T11:34:51.261Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@6f70642c
api02-1  | 2024-02-19T11:34:51.261Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api02-1  | 2024-02-19T11:34:51.263Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 9.22.3 by Redgate
api02-1  | 2024-02-19T11:34:51.263Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : See release notes here: https://rd.gt/416ObMi
api02-1  | 2024-02-19T11:34:51.263Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : 
api02-1  | 2024-02-19T11:34:51.263Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api02-1  | 2024-02-19T11:34:51.263Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api02-1  | 2024-02-19T11:34:51.264Z  INFO 1 --- [           main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:postgresql://db:5432/rinha (PostgreSQL 16.1)
api02-1  | 2024-02-19T11:34:51.264Z  WARN 1 --- [           main] o.f.c.internal.database.base.Database    : Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api02-1  | 2024-02-19T11:34:51.267Z  INFO 1 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Schema history table "public"."flyway_schema_history" does not exist yet
api02-1  | 2024-02-19T11:34:51.267Z  INFO 1 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 2 migrations (execution time 00:00.001s)
api02-1  | 2024-02-19T11:34:51.270Z  INFO 1 --- [           main] o.f.c.i.s.JdbcTableSchemaHistory         : Creating Schema History table "public"."flyway_schema_history" ...
api02-1  | 2024-02-19T11:34:51.296Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "public": << Empty Schema >>
api02-1  | 2024-02-19T11:34:51.298Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "public" to version "1.0.0 - cria tabelas"
api02-1  | 2024-02-19T11:34:51.317Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Migrating schema "public" to version "1.0.1 - clientes iniciais"
api02-1  | 2024-02-19T11:34:51.321Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Successfully applied 2 migrations to schema "public", now at version v1.0.1 (execution time 00:00.014s)
api01-1  | 2024-02-19T11:34:51.348Z  INFO 1 --- [           main] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.postgresql.jdbc.PgConnection@3176e4ea
api01-1  | 2024-02-19T11:34:51.348Z  INFO 1 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
api01-1  | 2024-02-19T11:34:51.351Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : Flyway Community Edition 9.22.3 by Redgate
api01-1  | 2024-02-19T11:34:51.351Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : See release notes here: https://rd.gt/416ObMi
api01-1  | 2024-02-19T11:34:51.351Z  INFO 1 --- [           main] o.f.c.internal.license.VersionPrinter    : 
api01-1  | 2024-02-19T11:34:51.351Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api01-1  | 2024-02-19T11:34:51.351Z  WARN 1 --- [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to scan location: /db/migration (unsupported protocol: resource)
api01-1  | 2024-02-19T11:34:51.352Z  INFO 1 --- [           main] org.flywaydb.core.FlywayExecutor         : Database: jdbc:postgresql://db:5432/rinha (PostgreSQL 16.1)
api01-1  | 2024-02-19T11:34:51.353Z  WARN 1 --- [           main] o.f.c.internal.database.base.Database    : Flyway upgrade recommended: PostgreSQL 16.1 is newer than this version of Flyway and support has not been tested. The latest supported version of PostgreSQL is 15.
api01-1  | 2024-02-19T11:34:51.356Z  INFO 1 --- [           main] o.f.core.internal.command.DbValidate     : Successfully validated 2 migrations (execution time 00:00.002s)
api01-1  | 2024-02-19T11:34:51.367Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Current version of schema "public": 1.0.1
api01-1  | 2024-02-19T11:34:51.368Z  INFO 1 --- [           main] o.f.core.internal.command.DbMigrate      : Schema "public" is up to date. No migration necessary.
api02-1  | 2024-02-19T11:34:51.447Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8081 (http) with context path ''
api02-1  | 2024-02-19T11:34:51.447Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Started RinhaApiApplication in 2.329 seconds (process running for 2.335)
api01-1  | 2024-02-19T11:34:51.520Z  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path ''
api01-1  | 2024-02-19T11:34:51.520Z  INFO 1 --- [           main] c.m.rinhaapi.RinhaApiApplication         : Started RinhaApiApplication in 2.29 seconds (process running for 2.298)
api01-1  | 2024-02-19T11:34:52.417Z  INFO 1 --- [omcat-handler-0] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
api01-1  | 2024-02-19T11:34:52.417Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
api01-1  | 2024-02-19T11:34:52.418Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
api02-1  | 2024-02-19T11:34:57.690Z  INFO 1 --- [omcat-handler-0] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
api02-1  | 2024-02-19T11:34:57.690Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
api02-1  | 2024-02-19T11:34:57.690Z  INFO 1 --- [omcat-handler-0] o.s.web.servlet.DispatcherServlet        : Completed initialization in 0 ms
db-1     | 2024-02-19 11:34:58.674 UTC [105] FATAL:  role "root" does not exist
api02-1  | 2024-02-19T11:35:01.740Z  WARN 1 --- [mcat-handler-52] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/5/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.740Z  WARN 1 --- [mcat-handler-56] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/2/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.740Z  WARN 1 --- [mcat-handler-55] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/3/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-19T11:35:01.742Z  WARN 1 --- [mcat-handler-55] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/2/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-19T11:35:01.743Z  WARN 1 --- [mcat-handler-56] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/1/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.744Z  WARN 1 --- [mcat-handler-58] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/3/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.744Z  WARN 1 --- [mcat-handler-59] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/5/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.745Z  WARN 1 --- [mcat-handler-60] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/4/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-19T11:35:01.745Z  WARN 1 --- [mcat-handler-58] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/1/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-19T11:35:01.746Z  WARN 1 --- [mcat-handler-57] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/2/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.747Z  WARN 1 --- [mcat-handler-61] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/3/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-19T11:35:01.747Z  WARN 1 --- [mcat-handler-59] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/5/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.749Z  WARN 1 --- [mcat-handler-63] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/4/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api01-1  | 2024-02-19T11:35:01.750Z  WARN 1 --- [mcat-handler-62] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/1/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
api02-1  | 2024-02-19T11:35:01.753Z  WARN 1 --- [mcat-handler-60] o.s.w.s.m.m.a.HttpEntityMethodProcessor  : public final org.springframework.http.ResponseEntity<java.lang.Object> org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler.handleException(java.lang.Exception,org.springframework.web.context.request.WebRequest) throws java.lang.Exception returned ResponseEntity: <422 UNPROCESSABLE_ENTITY Unprocessable Entity,ProblemDetail[type='about:blank', title='Bad Request', status=400, detail='Invalid request content.', instance='/clientes/4/transacoes', properties='null'],[]>, but its status doesn't match the ProblemDetail status: 400
db-1     | 2024-02-19 11:35:08.749 UTC [113] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:35:18.831 UTC [121] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:35:28.905 UTC [130] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:35:38.985 UTC [138] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:35:49.069 UTC [146] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:35:59.144 UTC [154] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:36:09.223 UTC [163] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:36:19.302 UTC [171] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:36:29.386 UTC [180] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:36:39.495 UTC [188] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:36:49.584 UTC [197] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:36:59.691 UTC [204] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:37:09.800 UTC [213] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:37:19.871 UTC [221] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:37:29.955 UTC [230] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:37:40.058 UTC [238] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:37:50.217 UTC [247] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:38:00.315 UTC [255] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:38:10.415 UTC [265] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:38:20.516 UTC [273] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:38:30.615 UTC [281] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:38:40.695 UTC [289] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:38:50.775 UTC [298] FATAL:  role "root" does not exist
db-1     | 2024-02-19 11:39:00.851 UTC [307] FATAL:  role "root" does not exist
nginx-1 exited with code 0
nginx-1 exited with code 0
api02-1  | 2024-02-19T11:39:06.033Z  INFO 1 --- [ionShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
api02-1  | 2024-02-19T11:39:06.034Z  INFO 1 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
api02-1  | 2024-02-19T11:39:06.035Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01-1  | 2024-02-19T11:39:06.041Z  INFO 1 --- [ionShutdownHook] o.s.b.w.e.tomcat.GracefulShutdown        : Commencing graceful shutdown. Waiting for active requests to complete
api02-1  | 2024-02-19T11:39:06.042Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api01-1  | 2024-02-19T11:39:06.044Z  INFO 1 --- [tomcat-shutdown] o.s.b.w.e.tomcat.GracefulShutdown        : Graceful shutdown complete
api01-1  | 2024-02-19T11:39:06.046Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
api01-1  | 2024-02-19T11:39:06.046Z  INFO 1 --- [ionShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
api02-1 exited with code 0
api02-1 exited with code 143
api01-1 exited with code 0
api01-1 exited with code 143
db-1     | 2024-02-19 11:39:07.236 UTC [1] LOG:  received fast shutdown request
db-1     | 2024-02-19 11:39:07.241 UTC [1] LOG:  aborting any active transactions
db-1     | 2024-02-19 11:39:07.243 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
db-1     | 2024-02-19 11:39:07.244 UTC [62] LOG:  shutting down
db-1     | 2024-02-19 11:39:07.248 UTC [62] LOG:  checkpoint starting: shutdown immediate
db-1     | 2024-02-19 11:39:07.459 UTC [62] LOG:  checkpoint complete: wrote 803 buffers (4.9%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.014 s, sync=0.182 s, total=0.216 s; sync files=80, longest=0.173 s, average=0.003 s; distance=4180 kB, estimate=4180 kB; lsn=0/1D28450, redo lsn=0/1D28450
db-1     | 2024-02-19 11:39:07.464 UTC [1] LOG:  database system is shut down
db-1 exited with code 0
