 Network rinha-2024q1  Creating
 Network rinha-2024q1  Created
 Container postgres  Creating
 Container postgres  Created
 Container deno-api-2  Creating
 Container deno-api-1  Creating
 api-2 The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested 
 Container deno-api-2  Created
 api-1 The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested 
 Container deno-api-1  Created
 Container arrudaricardo-01-caddy-1  Creating
 Container arrudaricardo-01-caddy-1  Created
Attaching to caddy-1, deno-api-1, deno-api-2, postgres
postgres    | The files belonging to this database system will be owned by user "postgres".
postgres    | This user must also own the server process.
postgres    | 
postgres    | The database cluster will be initialized with locale "en_US.utf8".
postgres    | The default database encoding has accordingly been set to "UTF8".
postgres    | The default text search configuration will be set to "english".
postgres    | 
postgres    | Data page checksums are disabled.
postgres    | 
postgres    | fixing permissions on existing directory /var/lib/postgresql/data ... ok
postgres    | creating subdirectories ... ok
postgres    | selecting dynamic shared memory implementation ... posix
postgres    | selecting default max_connections ... 100
postgres    | selecting default shared_buffers ... 128MB
deno-api-2  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
postgres    | selecting default time zone ... Etc/UTC
postgres    | creating configuration files ... ok
postgres    | running bootstrap script ... ok
caddy-1     | {"level":"info","ts":1708304601.218508,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
caddy-1     | {"level":"warn","ts":1708304601.2197099,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":3}
caddy-1     | {"level":"warn","ts":1708304601.220054,"logger":"admin","msg":"admin endpoint disabled"}
caddy-1     | {"level":"warn","ts":1708304601.2202702,"logger":"http.auto_https","msg":"automatic HTTPS is completely disabled for server","server_name":"srv0"}
caddy-1     | {"level":"info","ts":1708304601.220378,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc00038ce80"}
caddy-1     | {"level":"info","ts":1708304601.2208905,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
caddy-1     | {"level":"info","ts":1708304601.2212486,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
caddy-1     | {"level":"info","ts":1708304601.22126,"msg":"serving initial configuration"}
caddy-1     | {"level":"info","ts":1708304601.2301095,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/data/caddy"}
caddy-1     | {"level":"info","ts":1708304601.2303736,"logger":"tls","msg":"finished cleaning storage units"}
postgres    | performing post-bootstrap initialization ... ok
postgres    | initdb: warning: enabling "trust" authentication for local connections
postgres    | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
postgres    | syncing data to disk ... ok
postgres    | 
postgres    | 
postgres    | Success. You can now start the database server using:
postgres    | 
postgres    |     pg_ctl -D /var/lib/postgresql/data -l logfile start
postgres    | 
postgres    | waiting for server to start....2024-02-19 01:03:22.242 UTC [48] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres    | 2024-02-19 01:03:22.245 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres    | 2024-02-19 01:03:22.771 UTC [51] LOG:  database system was shut down at 2024-02-19 01:03:21 UTC
postgres    | 2024-02-19 01:03:22.860 UTC [48] LOG:  database system is ready to accept connections
postgres    |  done
postgres    | server started
deno-api-1 exited with code 1
deno-api-2 exited with code 1
postgres    | 
postgres    | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
postgres    | CREATE TABLE
postgres    | CREATE TABLE
postgres    | INSERT 0 1
postgres    | INSERT 0 1
postgres    | INSERT 0 1
postgres    | INSERT 0 1
postgres    | INSERT 0 1
postgres    | 
postgres    | 
postgres    | waiting for server to shut down...2024-02-19 01:03:23.232 UTC [48] LOG:  received fast shutdown request
postgres    | .2024-02-19 01:03:23.235 UTC [48] LOG:  aborting any active transactions
postgres    | 2024-02-19 01:03:23.238 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
postgres    | 2024-02-19 01:03:23.238 UTC [49] LOG:  shutting down
postgres    | 2024-02-19 01:03:23.240 UTC [49] LOG:  checkpoint starting: shutdown immediate
postgres    | 2024-02-19 01:03:23.380 UTC [49] LOG:  checkpoint complete: wrote 64 buffers (0.4%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.006 s, sync=0.118 s, total=0.142 s; sync files=46, longest=0.105 s, average=0.003 s; distance=179 kB, estimate=179 kB; lsn=0/1517648, redo lsn=0/1517648
postgres    | 2024-02-19 01:03:23.384 UTC [48] LOG:  database system is shut down
postgres    |  done
postgres    | server stopped
postgres    | 
postgres    | PostgreSQL init process complete; ready for start up.
postgres    | 
postgres    | 2024-02-19 01:03:23.456 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
postgres    | 2024-02-19 01:03:23.456 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres    | 2024-02-19 01:03:23.456 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres    | 2024-02-19 01:03:23.461 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres    | 2024-02-19 01:03:23.468 UTC [64] LOG:  database system was shut down at 2024-02-19 01:03:23 UTC
postgres    | 2024-02-19 01:03:23.516 UTC [1] LOG:  database system is ready to accept connections
deno-api-1 exited with code 1
deno-api-2 exited with code 1
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
caddy-1     | {"level":"error","ts":1708304609.5469866,"logger":"http.log.error","msg":"dial tcp 172.28.0.4:8080: connect: no route to host","request":{"remote_ip":"172.28.0.1","remote_port":"48238","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"Accept":["*/*"],"User-Agent":["curl/7.81.0"]}},"duration":6.661543504,"status":502,"err_id":"avwxbi5mq","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
caddy-1     | {"level":"error","ts":1708304617.734983,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"56170","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.180865528,"status":502,"err_id":"9emsg9t70","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
caddy-1     | {"level":"error","ts":1708304625.9049244,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"38580","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.162988805,"status":502,"err_id":"uqaaugihi","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1 exited with code 1
deno-api-2 exited with code 1
caddy-1     | {"level":"error","ts":1708304641.249293,"logger":"http.log.error","msg":"dial tcp 172.28.0.4:8080: i/o timeout","request":{"remote_ip":"172.28.0.1","remote_port":"38590","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":13.337505402,"status":502,"err_id":"twsf9kvqi","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304649.431676,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"53000","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.17537295,"status":502,"err_id":"t0ynvejce","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2 exited with code 1
deno-api-1 exited with code 1
caddy-1     | {"level":"error","ts":1708304667.343667,"logger":"http.log.error","msg":"dial tcp 172.28.0.3:8080: i/o timeout","request":{"remote_ip":"172.28.0.1","remote_port":"44472","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":15.905291454,"status":502,"err_id":"m2u90ix9x","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304675.5195684,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"46068","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.169001457,"status":502,"err_id":"fj0a8tzj1","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304683.7314808,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"46082","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.205151812,"status":502,"err_id":"9zyhrcsft","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304691.904042,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"37832","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"Accept":["*/*"],"User-Agent":["curl/7.81.0"]}},"duration":6.165567403,"status":502,"err_id":"8yma4n4ci","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304700.0874805,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"55532","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.176725456,"status":502,"err_id":"2uni4ikpc","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304708.2757192,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"40818","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.181357081,"status":502,"err_id":"qterndjrt","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2 exited with code 1
deno-api-1 exited with code 1
caddy-1     | {"level":"error","ts":1708304716.436704,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"49056","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.154121385,"status":502,"err_id":"39twm8p0k","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304724.6155415,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"49064","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.172109417,"status":502,"err_id":"a9f8qe7mw","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304732.791741,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"53366","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.169389196,"status":502,"err_id":"b471vn34k","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304740.9619994,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"49954","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.16345145,"status":502,"err_id":"5bpn8d7q9","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304749.1222296,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"54344","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.152987326,"status":502,"err_id":"4nbhxxjb5","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304757.2900229,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"57822","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.16126081,"status":502,"err_id":"hcx5rn8s8","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304765.457462,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"44332","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.160657927,"status":502,"err_id":"n80we6f9r","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-2  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-1  | exec ./main: exec format error
deno-api-2 exited with code 1
deno-api-1 exited with code 1
caddy-1     | {"level":"error","ts":1708304773.6384833,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-2 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"44336","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.174104017,"status":502,"err_id":"pnt1n09mc","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"error","ts":1708304781.8064733,"logger":"http.log.error","msg":"dial tcp: lookup deno-api-1 on 127.0.0.11:53: server misbehaving","request":{"remote_ip":"172.28.0.1","remote_port":"51120","client_ip":"172.28.0.1","proto":"HTTP/1.1","method":"GET","host":"localhost:9999","uri":"/clientes/1/extrato","headers":{"User-Agent":["curl/7.81.0"],"Accept":["*/*"]}},"duration":6.161028234,"status":502,"err_id":"wuy3f8q7s","err_trace":"reverseproxy.statusError (reverseproxy.go:1267)"}
caddy-1     | {"level":"info","ts":1708304783.9297833,"msg":"shutting down apps, then terminating","signal":"SIGTERM"}
caddy-1     | {"level":"warn","ts":1708304783.9298189,"msg":"exiting; byeee!! 👋","signal":"SIGTERM"}
caddy-1     | {"level":"info","ts":1708304783.929856,"logger":"http","msg":"servers shutting down with eternal grace period"}
caddy-1     | {"level":"info","ts":1708304783.929957,"msg":"shutdown complete","signal":"SIGTERM","exit_code":0}
caddy-1 exited with code 0
caddy-1 exited with code 0
deno-api-2 exited with code 0
deno-api-1 exited with code 0
postgres    | 2024-02-19 01:06:24.598 UTC [1] LOG:  received fast shutdown request
postgres    | 2024-02-19 01:06:24.600 UTC [1] LOG:  aborting any active transactions
postgres    | 2024-02-19 01:06:24.602 UTC [1] LOG:  background worker "logical replication launcher" (PID 67) exited with exit code 1
postgres    | 2024-02-19 01:06:24.602 UTC [62] LOG:  shutting down
postgres    | 2024-02-19 01:06:24.606 UTC [62] LOG:  checkpoint starting: shutdown immediate
postgres    | 2024-02-19 01:06:24.656 UTC [62] LOG:  checkpoint complete: wrote 24 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.007 s, sync=0.020 s, total=0.054 s; sync files=13, longest=0.006 s, average=0.002 s; distance=55 kB, estimate=55 kB; lsn=0/15255C8, redo lsn=0/15255C8
postgres    | 2024-02-19 01:06:24.660 UTC [1] LOG:  database system is shut down
postgres exited with code 0
